
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.WindowConstants;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Chatting extends javax.swing.JFrame implements Runnable {

    BufferedReader in;
    PrintWriter out;
    String line, pNum;
    String id;
    String pDate, pRole;

    public Chatting(int port, String id, String pNum, String pDate, String pRole) {
        // init client information
        this.id = id;
        this.pNum = pNum;
        this.pDate = pDate;
        this.pRole = pRole;
        try {
            // Make connection
            String serverAddress = "127.0.0.1";
            //getServerAddress();
            if (serverAddress == null || serverAddress.equals("")) {
                System.exit(0); // If IP address is wrong, finish the program.
            }
            // connect socket of server
            Socket socket = new Socket(serverAddress, port);

            //  Initialize streams
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            out = new PrintWriter(socket.getOutputStream(), true);

        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    public void run() {
        initComponents();   // init swing frame
        chatArea.setEditable(false);    // chat area set non-editable
        
        // window close --> one window
        this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent ev) {
                out.println("EXIT " + id + "`" + pNum + "`");
                dispose();//turn off a window
            }
        });
        this.setVisible(true);
        
        // chat start method.
        chatStart(in, out);
    }

    public void chatStart(BufferedReader inStream, PrintWriter outStream) {
        try {
            // communicate to server
            while (true) {
                line = in.readLine(); // receive data from server

                if (line.startsWith("con")) {
                    chatArea.append(line.substring(3) + "\n");
                } else if (line.startsWith("MESS")) {   // normal message OR whisper message
                    chatArea.append(line.substring(5) + '\n');
                } else if (line.startsWith("ROLE")) {   // message for role chat

                    //split data to role and message
                    String temp[] = line.substring(5).split("`");
                    
                    System.out.println(temp[0]);
                    System.out.println(temp[1]);

                    if (pRole.equals(temp[0])) {    // If role of this client sames role data of message
                        chatArea.append(temp[1] + '\n');    // print message
                    } else {
                        continue;
                    }
                }
                
                // The code that causes autoscroll to go down..
                jScrollPane1.getVerticalScrollBar().setValue(jScrollPane1.getVerticalScrollBar().getMaximum());
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatArea = new javax.swing.JTextArea();
        chatClient = new javax.swing.JTextField();
        event_button = new javax.swing.JButton();
        Voting = new javax.swing.JButton();
        Schedule = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chatArea.setBackground(new java.awt.Color(255, 255, 255));
        chatArea.setColumns(20);
        chatArea.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        chatArea.setForeground(new java.awt.Color(0, 0, 0));
        chatArea.setRows(5);
        jScrollPane1.setViewportView(chatArea);

        chatClient.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chatClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatClientActionPerformed(evt);
            }
        });

        event_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        event_button.setForeground(new java.awt.Color(153, 0, 0));
        event_button.setText("Finish Project");
        event_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_buttonActionPerformed(evt);
            }
        });

        Voting.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Voting.setForeground(new java.awt.Color(0, 0, 0));
        Voting.setIcon(new javax.swing.ImageIcon("C:\\Users\\hig97\\Desktop\\네트워크 그림\\icons8_Checked_Checkbox_30px.png")); // NOI18N
        Voting.setBorder(null);
        Voting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VotingActionPerformed(evt);
            }
        });

        Schedule.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Schedule.setForeground(new java.awt.Color(36, 47, 65));
        Schedule.setIcon(new javax.swing.ImageIcon("C:\\Users\\hig97\\Desktop\\네트워크 그림\\icons8_Schedule_30px.png")); // NOI18N
        Schedule.setBorder(null);
        Schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator1.setForeground(new java.awt.Color(36, 47, 65));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Enter");

        jSeparator2.setBackground(new java.awt.Color(36, 47, 65));
        jSeparator2.setForeground(new java.awt.Color(36, 47, 65));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hig97\\Desktop\\네트워크 그림\\icons8_Contacts_35px.png")); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chatClient)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(event_button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Voting)))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Voting))
                    .addComponent(event_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chatClient, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chatClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatClientActionPerformed
        // Send message event
        out.println("MESS " + id + "`" + pNum + "`" + chatClient.getText());
        chatClient.setText("");
    }//GEN-LAST:event_chatClientActionPerformed

    private void event_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_buttonActionPerformed
        // finish button click.
        
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");

        Date cday1 = null;
        Date cday2 = null;
        try {
            cday1 = date.parse(pDate);
            cday2 = date.parse(date.format(new Date()));
        } catch (ParseException e) {
            e.printStackTrace();
        }
        // Compares the current date with the due date, and if it is the same as or over the current date, 
        // it ends and sends an e-mail to the professor.
        int compare = cday1.compareTo(cday2);

        if (compare <= 0) {
            // send end message
            out.println("END " + id + "`" + pNum + "`");
            dispose();//turn off a window
        }
    }//GEN-LAST:event_event_buttonActionPerformed

    private void VotingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VotingActionPerformed
        // go the vote window, and send vote message to server
        out.println("VOTE");

        Voting vote;
        try {
            vote = new Voting(in, out);
            vote.setVisible(true);
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_VotingActionPerformed

    private void ScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleActionPerformed
        // go the Schedule window, and send Schedule message to server
        out.println("SCHEDULE");

        Schedule sch;
        try {
            sch = new Schedule(in, out);
        sch.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Chatting.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ScheduleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Schedule;
    private javax.swing.JButton Voting;
    private javax.swing.JTextArea chatArea;
    private javax.swing.JTextField chatClient;
    private javax.swing.JButton event_button;
    private javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
