
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.util.*;
import java.io.IOException;
import javax.swing.DefaultListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Kim B b
 */
public class CreateProject_IDlist extends javax.swing.JFrame {

    BufferedReader in;
    PrintWriter out;
    String line;
    Vector vecListID;
    Vector vecListTeam;

    /**
     * Creates new form CreateProject_IDlist
     */
    public void CreateProjectIDInit() {//initialize id list
        String myname="";
        vecListID = new Vector();
        vecListTeam = new Vector(); //create data list of id and team member
        try{
            System.out.println("bbbbbbbbbbbbbbbbb");
            out.println("myid ");          
            myname=in.readLine();
            System.out.println("aaaaaaaaaaaaa"+myname);
            vecListTeam.addElement(myname);
            
            printTeamList();
        }catch (IOException e) {
            e.printStackTrace();
        }
        out.println("PROJECTID");  //send to server to get IDs.

        try {
            while (true) {//get IDs
                line = in.readLine();//get id from server
                if (line.startsWith("PROJECTIDLIST")) {
                    if(line.substring(14).equals(myname))continue;
                    vecListID.addElement(line.substring(14));//add id to id data list
                    
                } else if (line.startsWith("IDEND")) {//if id list end
                    printIdList();//show id list to user
                    break;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public CreateProject_IDlist(BufferedReader inStream, PrintWriter outStream) {
        in = inStream;
        out = outStream;
         //get inputstream and outputstream from 'CreateProject.java'
        //and set 'CreateProject_IDlist.java''s input/outputstream
        
        initComponents();
        //create frame
        
        CreateProjectIDInit();
        //initialize id list
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WrongID = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DialogButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        idList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        teamList = new javax.swing.JList<>();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        WrongID.setMinimumSize(new java.awt.Dimension(420, 330));

        jPanel4.setMinimumSize(new java.awt.Dimension(420, 330));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wrong ID");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Check the ID list");

        DialogButton.setText("OK");
        DialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DialogButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(DialogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addComponent(DialogButton)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout WrongIDLayout = new javax.swing.GroupLayout(WrongID.getContentPane());
        WrongID.getContentPane().setLayout(WrongIDLayout);
        WrongIDLayout.setHorizontalGroup(
            WrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        WrongIDLayout.setVerticalGroup(
            WrongIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(36, 47, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idList.setBackground(new java.awt.Color(36, 47, 65));
        idList.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        idList.setForeground(new java.awt.Color(255, 255, 255));
        idList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        idList.setSelectionBackground(new java.awt.Color(153, 153, 255));
        idList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(idList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, 380));

        teamList.setBackground(new java.awt.Color(36, 47, 65));
        teamList.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        teamList.setForeground(new java.awt.Color(255, 255, 255));
        teamList.setSelectionBackground(new java.awt.Color(153, 153, 255));
        teamList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(teamList);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 200, 380));

        addButton.setBackground(new java.awt.Color(36, 47, 65));
        addButton.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText(">>");
        addButton.setBorder(null);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 60, 36));

        deleteButton.setBackground(new java.awt.Color(36, 47, 65));
        deleteButton.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("<<");
        deleteButton.setBorder(null);
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 60, 36));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADD TEAM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 200, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TEAM LIST");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial", 1, 21)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID LIST");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        okButton.setBackground(new java.awt.Color(36, 47, 65));
        okButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        okButton.setForeground(new java.awt.Color(255, 255, 255));
        okButton.setText("NEXT");
        okButton.setToolTipText("");
        okButton.setBorder(null);
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        jPanel1.add(okButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 80, 40));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\hig97\\Desktop\\네트워크 그림\\icons8_Arrow_35px.png")); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 510, 60, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printIdList() {
        idList.setListData(vecListID);//show id list to user

    }

    private void printTeamList() {
        teamList.setListData(vecListTeam); //show joined id list to user
    }

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
       //add member(s) choosed in idList to teamList
        
        String wantTeamId = idList.getSelectedValue();
        //get selected id
        
        vecListID.remove(idList.getSelectedIndex());
        //delete selected id from id data list

        idList.clearSelection();
        teamList.clearSelection();
        //clear selection both id list and joined id list


        // Performed if the data is not already added
        if (!vecListTeam.contains(wantTeamId) || wantTeamId == null) {
           try {
                out.println("IDCHECK " + wantTeamId);//send id to server to check
                String line;
                while (true) {
                    line = in.readLine();//get information from server

                    if (line.startsWith("IDACCEPT")) {
                        vecListTeam.add(wantTeamId);//add id to joined id list
                        printTeamList();
                        printIdList();
                        //show id and joinced id list to user
                        break;
                    } else if (line.startsWith("IDDENY")) {
                        WrongID.setVisible(true);//alert erroer to user
                        break;
                    }
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        //delete member(s) choosed in teamList to idList
        String temp = teamList.getSelectedValue();
        
        if(!(temp == null)){
            vecListID.addElement(teamList.getSelectedValue());
            vecListTeam.remove(teamList.getSelectedValue());
            idList.clearSelection();
            teamList.clearSelection();
        }
        
        //move selected data from joined id list to id list

        printIdList();
        printTeamList();
        //show id and joinced id list to user
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void DialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DialogButtonActionPerformed
        WrongID.setVisible(false); //close dialog
    }//GEN-LAST:event_DialogButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        //save project members and call 'CreateProject_Role.java' to set role of each member.

        if (teamList.getModel().getSize() != 0) {//the number of team member is bigger than 1
            dispose();//clost this frame
            new CreateProject_Role(in, out, vecListTeam).setVisible(true);
            //call 'CreateProject_Role.java' to set role of each member.
        }
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DialogButton;
    private javax.swing.JDialog WrongID;
    private javax.swing.JButton addButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JList<String> idList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okButton;
    private javax.swing.JList<String> teamList;
    // End of variables declaration//GEN-END:variables
}
